kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
networking:
  disableDefaultCNI: true # Desativa a rede padrão
  podSubnet: 192.168.0.0/16 # Faixa de IP exigida pelo Calico