apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-test
  template:
    metadata:
      labels:
        app: rbac-test
    spec:
      serviceAccountName: test-sa
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command:
            - sh
            - -c
            - kubectl get pods
